### ISSUE TITLE
Not python 3 compatible

### ISSUE THREAD

**Issue by kimthostrup** [raurodse/network_interfaces_parser#4]
Hi Raul,

When trying to upgrade my codebase to python3 (3.6.8) I get the following error:
----snip----
gunicorn3 --bind 127.0.0.1:6000 app:app
[2019-08-24 12:11:26 +0000] [5731] [INFO] Starting gunicorn 19.7.1
[2019-08-24 12:11:26 +0000] [5731] [INFO] Listening at: http://127.0.0.1:6000 (5731)
[2019-08-24 12:11:26 +0000] [5731] [INFO] Using worker: sync
[2019-08-24 12:11:26 +0000] [5734] [INFO] Booting worker with pid: 5734
[2019-08-24 12:11:28 +0000] [5734] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/var/wan-tester/netinterfaces.py", line 388, in load
    aux_stanza.set_option(" ".join(stanza_splited))
AttributeError: 'StanzaSource' object has no attribute 'set_option'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gunicorn/arbiter.py", line 578, in spawn_worker
    worker.init_process()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 135, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/lib/python3/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/lib/python3/dist-packages/gunicorn/util.py", line 377, in import_app
    __import__(module)
  File "/var/wan-tester/app.py", line 708, in <module>
    read_file(local_config.INPUT_INTERFACES)
  File "/var/wan-tester/app.py", line 678, in read_file
    app.network_interface.load(path_file)
  File "/var/wan-tester/netinterfaces.py", line 390, in load
    if ('has no attribute \'set_option\'' in e.message):
AttributeError: 'AttributeError' object has no attribute 'message'
[2019-08-24 12:11:28 +0000] [5734] [INFO] Worker exiting (pid: 5734)
[2019-08-24 12:11:28 +0000] [5731] [INFO] Shutting down: Master
[2019-08-24 12:11:28 +0000] [5731] [INFO] Reason: Worker failed to boot.
----snip----

Any idea how to fix this problem ?

Thanks in advance

**Comment by kimthostrup** [comment]
Never mind, the issue had nothing to do with the python version, but rather the fact that ubuntu 18.x has this in the top of the interface file
----snip----
source /etc/network/interfaces.d/*
# The loopback network interface
----snip----
